language: rust

os:
  - linux

rust:
  - stable
  - beta
  - nightly

script:
  - cargo build --verbose --all
  - cargo test --verbose --all
  - cargo build --verbose --all --release

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

deploy:
  provider: releases
  api_key:
    secure: j6hloIdfg+9uaDRRLcCfbg2vZnQZZouD98JB/c3sIm6/OFJ/UMKxBM9oGOKurcw4vnD1Hp85PCOJqP4RQhKpbDgw2ePqjsXXsz0yAl+GhKRRFG9Q126zKEreSAZox5fE0GpYuGXOGkOIFYp9KXRWttA5/YyjrmSMCP10boK88DlOeNHb4nB2PGhpoN6EB8iPnL7ROEPG4jzetp4KM9jV1uvfgEnvsj6w0JlTatismyrTzYq8T8i4EngXE9hx4jD/R1eROPVH8EpMj6l9k+y+2OVn3ONpBmzaL1YYzbSYUGtFa2aO0OJd8RKCNZU3R5dsEOqDTepsMWM3B084Fw61fcYU4oKMAKLoXrPlfySPxkepTSGSQSCbJe770Bq1MFnCJp0d+3SI2TU9Gpv14Z5UNMNlzczQtWnKqnZ8Jqp5Gt7Gtwsozex+z6GyrkLaRR5xz51ZdVxVSh29qTTDtWKvDvopKP2IBiJ0SLozdrxYiQe0E2GpeRhv4HNMxh4YO3CN2J8OGX3+MPkJKoYYMbfphtddiC1yA3LiV8jz3Uhv+C2J7qR6H/+4fIeht2odB0SMS6JXnOg4B81daYkNVmgABMsx7K/8rSy0Pza+dCRpiBfyuKiOkTHiBUNnE6YmpTn+m2izOq9i9U2dpY4yy9FydYiGQD8MpOq77loNiSeAk6c=
  file: ./target/release/rstow
  skip_cleanup: true
  on:
    repo: qboileau/rstow
    tags: true
